apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "otel-collector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
