apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ include "otel-collector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "otel-collector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
