{
 "title": "Kubernetes Clusters ( OTEL )",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values({\"k8s.node.condition_ready\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Readiness",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "({\"k8s.node.condition_ready\", cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{k8s.node.name}}"
    },
    {
     "expr": "-({\"k8s.node.condition_ready\", cluster=\"$cluster\"} == -1)",
     "legendFormat": "{{k8s.node.name}}"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "({\"k8s.node.condition_disk_pressure\", cluster=\"$cluster\"} == 0) + 1",
     "legendFormat": "{{k8s.node.name}}"
    },
    {
     "expr": "({\"k8s.node.condition_disk_pressure\", cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{k8s.node.name}}"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "({\"k8s.node.condition_memory_pressure\", cluster=\"$cluster\"} == 0) + 1",
     "legendFormat": "{{k8s.node.name}}"
    },
    {
     "expr": "({\"k8s.node.condition_memory_pressure\", cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{k8s.node.name}}"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "({\"k8s.node.condition_network_unavailable\", cluster=\"$cluster\"} == 0) + 1",
     "legendFormat": "{{k8s.node.name}}"
    },
    {
     "expr": "({\"k8s.node.condition_network_unavailable\", cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{k8s.node.name}}"
    }
   ]
  },
  {
   "title": "Pid Pressure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "({\"k8s.node.condition_pid_pressure\", cluster=\"$cluster\"} == 0) + 1",
     "legendFormat": "{{k8s.node.name}}"
    },
    {
     "expr": "({\"k8s.node.condition_pid_pressure\", cluster=\"$cluster\"} == 1)",
     "legendFormat": "{{k8s.node.name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"k8s.node.cpu.usage\", cluster=\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum({\"k8s.container.cpu_request\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum({\"k8s.container.cpu_limit\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum({\"system.cpu.logical.count\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum({\"k8s.node.cpu.usage\", cluster=\"$cluster\"})",
     "legendFormat": "Cores Used"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"k8s.node.cpu.usage\", cluster=\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum({\"k8s.container.cpu_request\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum({\"k8s.container.cpu_limit\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum({\"system.cpu.logical.count\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({\"k8s.node.memory.usage\", cluster=\"$cluster\"})",
     "legendFormat": "RAM Utilization"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "100 *\n(\n  {\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}\n  -\n  {\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}\n)\n/\n{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"} - {\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Network usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({\"k8s.pod.network.io\",cluster=\"$cluster\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "recieve"
    },
    {
     "expr": "- sum(rate({\"k8s.pod.network.io\",cluster=\"$cluster\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network usage (packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate({\"system.network.packets\",cluster=\"$cluster\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate({\"system.network.packets\",cluster=\"$cluster\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}