{
 "title": "NETWORK",
 "tags": [ "Do not delete this dashbaord" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nvswitch_lldp_neighbor_info,instance)"
    }
   },
   {
    "name": "8100",
    "label": "instance:8100",
    "query": {
     "query": "label_values(nvswitch_interface_discards_loopback_filter,instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 } },
  { "title": "Interfaces with problems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Bond went down",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  nvswitch_interface_info{operstate=\"up\", instance=~\"$instance\"} == 1\r\n) * 1\r\n",
     "legendFormat": "{{ifalias}}"
    }
   ]
  },
  {
   "title": "Interfaces went down within 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(nvswitch_interface_oper_state{instance=~\"$instance\"} == 2\r\n  or nvswitch_interface_oper_state{instance=~\"$instance\"} == 8)\r\nand on(instance, interface)\r\n  (changes(nvswitch_interface_oper_state{instance=~\"$instance\"}[5m]) > 0)\r\n",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "(changes(nvswitch_interface_oper_state{instance=~\"$8100\"}[5m]) > 1)",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Proto and carrier down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "increase(nvswitch_interface_proto_down_total{instance=~\"$instance\"}[5m]) > 0\r\n",
     "legendFormat": "protodown {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_carrier_down_changes_total{instance=~\"$instance\"}[5m]) > 0\r\n",
     "legendFormat": "carrierdown {{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Interfaces with FCS, PHY, and CRC_Align Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "increase(nvswitch_interface_dot3_stats_fcs_errors{instance=~\"$8100\"}[5m])  > 0\r\n",
     "legendFormat": "fcs: {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_phy_stats_phy_effective_errors[5m]) > 0",
     "legendFormat": "phy: {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_ether_stats_crc_align_errors[5]) > 0",
     "legendFormat": "crc: {{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "txwait, drops and buffer ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_ether_stats_jabbers{instance=~\"$instance\"}[5m]) > 0",
     "legendFormat": "jabbers: {{instance}} {{interface}}"
    },
    {
     "expr": "rate(nvswitch_interface_tx_int_cksm_err[5m]) > 0",
     "legendFormat": "tx_cksm_err: {{instance}} {{interface}}"
    },
    {
     "expr": "rate(nvswitch_interface_rx_buffer_full[5m]) > 0",
     "legendFormat": "rx_buf_full: {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_ether_stats_drop_events[1m]) > 0",
     "legendFormat": "ether_stats_drop: {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_no_buffer_discard_mc[1m]) > 0",
     "legendFormat": "no_buffer_discard_mc: {{instance}} {{interface}}"
    },
    {
     "expr": "increase(nvswitch_interface_tx_wait[1m]) > 0",
     "legendFormat": "tx_wait {{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "incoming packets/frames errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "increase(nvswitch_interface_if_in_errors{instance=~\"$8100\"}[1m]) > 0\r\n",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "symbol errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "nvswitch_interface_dot3_stats_symbol_errors{instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "outgoing packets/frames errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_if_out_errors{instance=~\"$8100\"}[5m]) > 0",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Ingress Discards",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(nvswitch_interface_discards_ingress_general{instance=~\"$8100\"}[5m]) > 0)\r\nand on(interface, switch) (nvswitch_interface_oper_state{instance=~\"$8100\"} == 1) ",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Packet discards due to loop detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "increase(nvswitch_interface_discards_loopback_filter{instance=~\"$8100\"}[5m]) > 0",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Discards Egress STP filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(nvswitch_interface_discards_egress_stp_filter{instance=~\"$8100\"}[5m]) > 0",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "outgoing discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": " increase(nvswitch_interface_if_out_discards{instance=~\"$8100\"}[1m]) > 0",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Platform Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "FAN and PSU  STATUS",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvswitch_platform_environment_fan_state",
       "legendFormat": "{{instance}} {{Value}}"
      },
      {
       "expr": "nvswitch_platform_environment_psu_state",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvswitch_platform_environment_temp_current{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} {{description}}"
      }
     ]
    },
    {
     "title": "CPU throttle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by(instance) (increase(node_cpu_core_throttles_total[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IOWait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "100 *\r\nsum by(instance) (rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))\r\n/\r\nsum by(instance) (rate(node_cpu_seconds_total[5m]))\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "total CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\r\n  1 -\r\n  sum by(instance) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n  )\r\n  /\r\n  sum by(instance) (\r\n    rate(node_cpu_seconds_total[5m])\r\n  )\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(\r\n  node_memory_MemTotal_bytes\r\n- node_memory_MemFree_bytes\r\n- node_memory_Buffers_bytes\r\n- node_memory_Cached_bytes\r\n) \r\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "node_memory_MemAvailable_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes\r\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Buffers and Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
       "legendFormat": "buffer {{instance}}"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
       "legendFormat": "cache {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Used in Bytes (per instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes\r\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Swap Usage %",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)\r\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage % (per instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total disk write time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_disk_write_time_seconds_total",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Switch Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      { "expr": "node_disk_io_now", "legendFormat": "{{instance}} {{device}}" }
     ]
    },
    {
     "title": "transceiver channel power",
     "type": "table",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "nvswitch_platform_transceiver_channel_power{instance=~\"$8100\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "transceiver temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nvswitch_platform_transceiver_temperature{instance=~\"$8100\"}",
       "legendFormat": "{{instance}} {{port}} {{Value}} "
      }
     ]
    },
    {
     "title": "Transceiver vendor info",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "nvswitch_platform_transceiver_vendor_info{instance=~\"$8100\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Reboot",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "nvswitch_platform_info_last_reboot_time / 1e6\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "nvswitch_platform_info_last_reboot_reason",
     "legendFormat": "__auto"
    },
    {
     "expr": "nvswitch_platform_info_firmware_version",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Ports Info",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "nvswitch_interface_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "nvswitch_interface_mtu_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLDP",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "nvswitch_lldp_neighbor_info{instance=~\"$instance\"}\r\n",
     "legendFormat": "{{instance}} {{interface}} {{port_description}}"
    }
   ]
  }
 ]
}