apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-plugins-provisioning
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: observability-central
data:
  plugins.yaml: |
{{ printf "%s" (.Files.Get "config/grafana/provisioning/plugins/plugins.yaml") | indent 4 }}
