{
 "title": "WAZUH - MITRE ATT&CK",
 "description": "Wazuh MITRE ATT&CK (dot fields). agent.name, @timestamp, rule.mitre.*",
 "tags": [
  "wazuh",
  "security",
  "alerts"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent.name\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "MITRE ATT&CK ENRICHMENT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "MITRE ENRICHED EVENTS",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(_exists_:rule.mitre.tactic OR _exists_:rule.mitre.technique OR _exists_:rule.mitre.id) AND agent.name:$agent_name",
     "timeField": "@timestamp"
    },
    {
     "alias": "ALL EVENTS",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND _exists_:rule.mitre.technique",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TOP 10 AGENTS",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND (_exists_:rule.mitre.tactic OR _exists_:data.win.eventdata.ruleName)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TACTICS (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.tactic",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND _exists_:rule.mitre.tactic",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND (_exists_:rule.mitre.tactic OR _exists_:data.win.eventdata.ruleName)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TACTICS",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.tactic",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TELEMETRY",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "agent.name:$agent_name AND (_exists_:rule.mitre.tactic OR _exists_:data.win.eventdata.ruleName)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}