events { worker_connections 1024; }
http {
  upstream grafana_upstream { server grafana:3000; }
  server {
    listen 80;
    location / {
      proxy_pass http://grafana_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
