{
 "title": "WAZUH - FIM",
 "description": "Wazuh - FIM (dot fields). Usa agent.name, @timestamp, rule.level, rule.groups, syscheck.*",
 "tags": [
  "wazuh",
  "alerts",
  "security"
 ],
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent.name\", \"query\": \"\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule.level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Events (TOTAL)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND \"syscheck\" AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Trend Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND \"syscheck\" AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Agents with Most File Changes",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "\"syscheck\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FILE CHANGES",
   "type": "piechart",
   "description": "Modified / Added / Deleted",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syscheck.event",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"syscheck\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Changed Files",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syscheck.path",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"syscheck\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Real Time Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "\"syscheck\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MODIFIED FILES",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syscheck.path",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"Integrity checksum changed\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ADDED FILES",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syscheck.path",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"File added\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DELETED FILES",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "syscheck.path",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "\"File deleted\" AND agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}