{
 "title": "OpenStack Projects",
 "tags": [
  "openstack",
  "cloud"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "Project",
    "query": {
     "query": "label_values(openstack_project_usage,project_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Project Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(openstack_project_usage{project_name=\"${project_name}\"}) by (placement_resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources per Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(avg_over_time(openstack_project_usage{project_name=\"${project_name}\"}[30m:])) by (placement_resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(openstack_project_quota{project_name=~\"${project_name}\"}[30m:])",
     "legendFormat": "{{quota_resource}}"
    }
   ]
  },
  {
   "title": "Servers by flavor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "count(count(libvirt_domain_openstack_info{project_name=~\"${project_name}\"}) by (domain,flavor_name)) by (flavor_name)",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(irate(libvirt_domain_vcpu_time_seconds_total{}[5m]) / ignoring(instance,vcpu) group_left(domain) libvirt_domain_info_virtual_cpus{}) by (domain) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}) by (project_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(libvirt_domain_memory_stats_used_percent * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}) by (project_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(libvirt_domain_block_stats_read_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}) by (project_name)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(libvirt_domain_block_stats_write_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"} * -1) by (project_name)",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Per Instance Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_vcpu_time_seconds_total{}[5m]) / ignoring(instance,vcpu) group_left(domain) libvirt_domain_info_virtual_cpus{}) by (domain) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk utilization per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"}",
     "legendFormat": "{{instance_name}} : read {{target_device}}"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_openstack_info{project_name=~\"${project_name}\"} * -1",
     "legendFormat": "{{instance_name}} : write {{target_device}}"
    }
   ]
  }
 ]
}