{
 "title": "Kubernetes Cluster Nodes",
 "tags": [
  "conversion",
  "kubernetes",
  "nodes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values({\"k8s.node.condition_ready\"},cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values({\"k8s.node.condition_ready\", cluster=\"$cluster\"},k8s.node.name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({\"k8s.pod.phase\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"},k8s.namespace.name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"k8s.node.cpu.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}) / sum({\"system.cpu.logical.count\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$usage / $capacity\n", "type": "math" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"k8s.node.filesystem.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"})\n/\nsum({\"k8s.node.filesystem.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({\"k8s.pod.phase\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"k8s.node.uptime\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"k8s.node.condition_ready\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{\"k8s.node.cpu.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
       "legendFormat": "$node"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum({\"k8s.node.memory.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}\n  - {\"k8s.node.memory.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"})\n/\nsum({\"k8s.node.memory.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"})",
       "legendFormat": "{{k8s.node.name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{\"k8s.node.filesystem.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "{\"k8s.node.filesystem.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "{\"k8s.node.filesystem.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
       "legendFormat": "available"
      }
     ]
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "List of pods on node",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{\"k8s.pod.phase\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{\"k8s.pod.cpu.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\"}",
     "legendFormat": "{{k8s.pod.name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"k8s.pod.memory.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\"}",
     "legendFormat": "{{k8s.pod.name}}"
    }
   ]
  },
  {
   "title": "Memory RSS by Pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"k8s.pod.memory.rss\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\"}",
     "legendFormat": "{{k8s.pod.name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network Usage ( bytes ) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({\"k8s.pod.network.io\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate({\"k8s.pod.network.io\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\", \"k8s.namespace.name\"=~\"$namespace\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Usage ( packets ) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate({\"system.network.packets\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\",direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate({\"system.network.packets\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\",direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Volume Usage %",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "100 *\n(\n  {\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}\n  -\n  {\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}\n)\n/\n{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"} - {\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    },
    {
     "expr": "{\"k8s.volume.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\", \"k8s.volume.type\"=\"persistentVolumeClaim\"}",
     "legendFormat": "{{k8s.persistentvolumeclaim.name}}"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Disk Read ( Bytes )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({\"system.disk.io\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\", direction=\"read\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write ( Bytes )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({\"system.disk.io\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\", direction=\"write\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"k8s.node.filesystem.available\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
     "legendFormat": "available"
    },
    {
     "expr": "{\"k8s.node.filesystem.usage\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{\"k8s.node.filesystem.capacity\", cluster=\"$cluster\", \"k8s.node.name\"=\"$node\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "FS Inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"system.filesystem.inodes.usage\",cluster=\"$cluster\",\"k8s.node.name\"=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}