{
 "title": "Blackbox Exporter (HTTP prober) — Production",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\", instance!~\".*/.+\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "graph",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "https://otel.yourdomain.tld", "type": "row", "gridPos": { "x": 0, "y": 18, "w": 24, "h": 1 } },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase",
   "gridPos": { "x": 0, "y": 19, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=\"https://otel.yourdomain.tld\"}",
     "legendFormat": "{{{{phase}}}}"
    }
   ]
  },
  { "title": "https://grafana.yourdomain.tld", "type": "row", "gridPos": { "x": 0, "y": 26, "w": 24, "h": 1 } },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=\"https://grafana.yourdomain.tld\"}",
     "legendFormat": "{{{{phase}}}}"
    }
   ]
  },
  {
   "title": "https://vault.assembly.yourdomain.tld",
   "type": "row",
   "gridPos": { "x": 0, "y": 34, "w": 24, "h": 1 }
  },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase",
   "gridPos": { "x": 0, "y": 35, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=\"https://vault.assembly.yourdomain.tld\"}",
     "legendFormat": "{{{{phase}}}}"
    }
   ]
  },
  {
   "title": "https://argocd.assembly.yourdomain.tld",
   "type": "row",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 1 }
  },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase",
   "gridPos": { "x": 0, "y": 43, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=\"https://argocd.assembly.yourdomain.tld\"}",
     "legendFormat": "{{{{phase}}}}"
    }
   ]
  }
 ]
}